export const routes = {
  SIGN_UP: '/signUp',
  SIGN_IN: '/sign-in',
  JOBS: '/jobs',
  COLLEGEPROFILE: '/collegeProfile',
  PLACEMENTPROFILE: '/placementPolicy',
  EDITPROFILE: '/editProfile',
  EDITPLACEMENTPROFILE: '/editPlacementPolicy',
  STUDENTPROFILE: '/studentProfile',
  EDITSTUDENTPROFILE: '/editStudentProfile',
  COMPANYPROFILE: '/companyProfile',
  EDITCOMPANYPROFILE: '/editCompanyProfile',
  NOTFOUND: '/404',
  USERMANAGEMENT: '/userManagement',
  STUDENTLIST: '/studentList',
  TPODASHBOARD: '/dashboard/College',
  COMPANYDASHBOARD: '/dashboard/Company',
  UPLOADSTUDENTRESUME: '/uploadStudentResume',
}
